.MODEL SMALL 

.STACK 100H

.DATA

    MATRIZ4X4 DB 1,2,3,4
              DB 4,3,2,1
              DB 5,6,7,8
              DB 8,7,6,5

.CODE

    PULA_LINHA MACRO            ;MACRO PARA PULAR LINHA
        PUSH AX 
        PUSH DX

        MOV AH,2
        MOV DL,10
        INT 21H

        MOV AH,2
        MOV DL,13
        INT 21H

        POP DX
        POP AX

    ENDM

    ;PROCEDIMENTO PARA IMPRIMIR MATRIZ (ENTRADA: MATRIZ SAÍDA: VOID)
    IMPRIMIR_MATRIZ PROC

        XOR BX,BX;ZERA BX
        PUSH AX;AX NO TOPO DA PILHA


        MOV AH,2;IMPRIMIR CARACTER
        

        RESET:
            MOV CX,4;CONTADOR 4
            XOR SI,SI;ZERA SI
        IMPRIME:
            MOV DL,MATRIZ4X4[BX][SI];DL VIRA A MATRIZ DA POSICAO BX E SI
            ADD DL,'0';CONVERTE EM CARACTER
            INT 21H
            INC SI;INCREMENTA SI
            LOOP IMPRIME;LOOP NO LABEL IMPRIME

            ADD BX,4 ;ADICIONA 4 EM BX 
            PULA_LINHA ;PULA LINHA
            CMP BX,12;COMPARA 12 COM BX
            JBE RESET;PULA SE MENOR OU IGUAL
        
        RET;RETORNA MAIN

    IMPRIMIR_MATRIZ ENDP

    MAIN PROC
        MOV AX,@DATA;PERMITE ACESSO AO SEGMENTO DE DADOS
        MOV DS,AX

        CALL IMPRIMIR_MATRIZ;CHAMA PROCEDIMENTO

        MOV AH,4CH;FINALIZA O PROGRAMA
        INT 21H
    MAIN ENDP
END MAIN