.MODEL SMALL

.STACK 100H

.DATA

    ENTRADA DB 'ESCOLHA A ENTRADA:$' 
    BINARIO DB 10,13, '1.BINARIO$'
    HEXADECIMAL DB 10,13, '2.HEXADECIMAL$'
    DECIMAL DB 10,13,'3.DECIMAL$'
    DIGITE DB 10,13, 'DIGITE: $'
.CODE

    IMPRIME_TABELA MACRO STRING1,STRING2,STRING3,STRING4

    PUSH AX

    MOV AH,9

    LEA DX,STRING1
    INT 21H
    LEA DX,STRING2
    INT 21H
    LEA DX,STRING3
    INT 21H
    LEA DX,STRING4
    INT 21H
    POP AX
    ENDM

    ;description
    MAIN PROC
      MOV AX,@DATA
      MOV DS,AX

     IMPRIME_TABELA ENTRADA,BINARIO,HEXADECIMAL,DECIMAL
    MAIN ENDP
END MAIN